test 12

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,16 @@
 #!/bin/sh
-yarn lint
-if [ $? -ne 0 ]; then
+lint_output=$(yarn lint)
+lint_exit_code=$?
+
+echo "$lint_output"  # Output the lint result
+
+if [ $lint_exit_code -ne 0 ]; then
   echo "Lint errors found. Commit aborted."
+  exit 1
+fi
+
+warning_count=$(echo "$lint_output" | grep -c "warning:")
+if [ $warning_count -ne 0 ]; then
+  echo "Lint warnings found. Commit aborted."
   exit 1
 fi
